namespace DriverStore
{
    public enum ProcessorArchitecture : ushort
    {
        PROCESSOR_ARCHITECTURE_INTEL,
        PROCESSOR_ARCHITECTURE_MIPS,
        PROCESSOR_ARCHITECTURE_ALPHA,
        PROCESSOR_ARCHITECTURE_PPC,
        PROCESSOR_ARCHITECTURE_SHX,
        PROCESSOR_ARCHITECTURE_ARM,
        PROCESSOR_ARCHITECTURE_IA64,
        PROCESSOR_ARCHITECTURE_ALPHA64,
        PROCESSOR_ARCHITECTURE_MSIL,
        PROCESSOR_ARCHITECTURE_AMD64,
        PROCESSOR_ARCHITECTURE_IA32_ON_WIN64,
        PROCESSOR_ARCHITECTURE_NEUTRAL,
        PROCESSOR_ARCHITECTURE_ARM64
    }
}
